version: 0.2

env:
  variables:
    SLS_DEBUG: '*'
    CI: true

phases:
  pre_build:
    commands:
      - npm install

  build:
    commands:
      - sls remove
      - npm run test:unit
      - npm run test:coverage
      - npm run deploy:dev
