---
AWSTemplateFormatVersion: "2010-09-09"
Description: ECS Infrastructure

Parameters:
  Hostname:
    Type: String

  Environment:
    Type: String

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name: !Ref Hostname
      HostedZoneConfig:
        Comment: My hosted zone ECS

Outputs:
  HostedZone:
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'HostedZone']]
    Value: !Ref HostedZone
