Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-05b48eda7f92aadbe
      InstanceType: t3.small

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 1
      LifecycleHookSpecificationList:
        - LifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
          LifecycleHookName: 'InstanceCreationLifeCycleHook'
          HeartbeatTimeout: 300
          NotificationTargetARN: !Ref SupportSNSTopic

  SupportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ECS AutoScaling Group Topic
      TopicName: ECS_ASG_Topic
