Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-05b48eda7f92aadbe
      InstanceType: t3.small

  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 1
      LifecycleHookSpecificationList:
        - LifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
          LifecycleHookName: 'InstanceCreationLifeCycleHook'
          HeartbeatTimeout: 300
          NotificationTargetARN: !Ref SupportSNSTopic
          RoleARN: !GetAtt LifecycleRole.Arn

  LifecycleRole:
    Type: AWS::IAM::Role
    Properties:
      Path:
      AssumeRolePolicyDocument:
      Policies:
        -
          PolicyName: "Lifecycle Hook Role"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action: "*"
                Resource: "*"

  SupportSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ECS AutoScaling Group Topic
      TopicName: ECS_ASG_Topic
