Resources:
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-05b48eda7f92aadbe
      InstanceType: t3.small

  AutoScalingGroup:
    DependsOn:
      - LifecycleRole
      - ASGSNSTopic
      - ASGSNSTopicPolicy
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AvailabilityZones: !GetAZs ''
      LaunchConfigurationName: !Ref LaunchConfiguration
      MaxSize: 1
      MinSize: 1

  LifecycleHook:
    Type: AWS::AutoScaling::LifecycleHook
    Properties:
      AutoScalingGroupName: !Ref AutoScalingGroup
      DefaultResult: CONTINUE
      HeartbeatTimeout: 300
      LifecycleTransition: 'autoscaling:EC2_INSTANCE_LAUNCHING'
      NotificationTargetARN: !Ref ASGSNSTopic
      RoleARN: !GetAtt LifecycleRole.Arn

  LifecycleRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Action:
            - 'sts:AssumeRole'
          Effect: Allow
          Principal:
            AWS: "*"
        Version: '2012-10-17'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AutoScalingNotificationAccessRole

  ASGSNSTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: ECS AutoScaling Group Topic
      TopicName: ECS_ASG_Topic

  ASGSNSTopicPolicy:
    Type: AWS::SNS::TopicPolicy
    Properties:
      PolicyDocument:
        Id: ECS_ASG_Topic_Policy
        Version: '2012-10-17'
        Statement:
        - Sid: AllowLifecycleRole
          Effect: Allow
          Principal:
            AWS: "*"
          Action: sns:Publish
          Resource: "*"
      Topics:
      - !Ref ASGSNSTopic

  SSMMountDocument:
    Type: AWS::SSM::Document
    Properties:
      Content:
        schemaVersion: "2.2"
        description: "Command document for mounting the EBS volume"
        mainSteps:
        - action: "aws:runShellScript"
          name: "Mount EBS Volume"
          inputs:
            runCommand:
            - "mount /dev/xdvy /data"
      DocumentType: YAML

Outputs:
  TopicArn:
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'TopicArn']]
    Value: !Ref ASGSNSTopic

  DocumentName:
    Export:
      Name: !Join ['-', [!Ref 'AWS::StackName', 'Document']]
    Value: !Ref SSMMountDocument
