service:
  name: ecs-disaster-recovery

plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs8.10

functions:
  ecs-disaster-recovery:
    handler: src/autoScaleUp.handler
    environment:
      MASTER_VOLUME_TABLE: {"Ref": MasterVolumeTable}
      SUPPORT_SNS_TOPIC_ARN: {"Ref": SupportSNSTopic}

resources:
  Resources:
    MasterVolumeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 2
          WriteCapacityUnits: 2
        SSESpecification:
          SSEEnabled: true

    SupportSNSTopic:
      Type: AWS::SNS::Topic
      Properties:
        DisplayName: ECS Support Topic
        TopicName: ECS_Support_Topic
